{"level":"error","message":"Failed to connect to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:816:11)\n    at NativeConnection.openUri (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:791:11)\n    at async connectDatabase (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/config/database.js:54:5)\n    at async startServer (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/server.js:71:5)","timestamp":"2025-10-01 13:20:33"}
{"level":"error","message":"Failed to connect to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:816:11)\n    at NativeConnection.openUri (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:791:11)\n    at async connectDatabase (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/config/database.js:54:5)\n    at async startServer (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/server.js:71:5)","timestamp":"2025-10-01 13:20:33"}
{"level":"error","message":"Failed to connect to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:816:11)\n    at NativeConnection.openUri (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:791:11)\n    at async connectDatabase (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/config/database.js:54:5)\n    at async startServer (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/server.js:71:5)","timestamp":"2025-10-01 13:20:47"}
{"level":"error","message":"Failed to connect to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:816:11)\n    at NativeConnection.openUri (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:791:11)\n    at async connectDatabase (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/config/database.js:54:5)\n    at async startServer (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/server.js:82:5)","timestamp":"2025-10-01 13:46:21"}
{"level":"error","message":"Failed to connect to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:816:11)\n    at NativeConnection.openUri (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:791:11)\n    at async connectDatabase (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/config/database.js:54:5)\n    at async startServer (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/server.js:82:5)","timestamp":"2025-10-01 13:51:15"}
{"level":"error","message":"Failed to connect to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:816:11)\n    at NativeConnection.openUri (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:791:11)\n    at async connectDatabase (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/config/database.js:54:5)\n    at async startServer (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/server.js:82:5)","timestamp":"2025-10-01 13:51:59"}
{"level":"error","message":"Failed to connect to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:816:11)\n    at NativeConnection.openUri (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:791:11)\n    at async connectDatabase (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/config/database.js:54:5)\n    at async startServer (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/server.js:82:5)","timestamp":"2025-10-01 13:55:53"}
{"level":"error","message":"Failed to connect to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:816:11)\n    at NativeConnection.openUri (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:791:11)\n    at async connectDatabase (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/config/database.js:54:5)\n    at async startServer (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/server.js:82:5)","timestamp":"2025-10-01 13:56:38"}
{"level":"error","message":"Failed to start server: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:816:11)\n    at NativeConnection.openUri (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:791:11)\n    at async connectDatabase (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/config/database.js:54:5)\n    at async startServer (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/server.js:82:5)","timestamp":"2025-10-01 13:56:38"}
{"level":"error","message":"MongoDB connection error: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at Timeout._onTimeout (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongodb\\lib\\sdam\\topology.js:278:38)\n    at listOnTimeout (node:internal/timers:588:17)\n    at process.processTimers (node:internal/timers:523:7)","timestamp":"2025-10-01 13:56:38"}
{"level":"error","message":"Failed to connect to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:816:11)\n    at NativeConnection.openUri (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:791:11)\n    at async connectDatabase (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/config/database.js:54:5)\n    at async startServer (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/server.js:82:5)","timestamp":"2025-10-01 13:57:21"}
{"level":"error","message":"Failed to start server: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:816:11)\n    at NativeConnection.openUri (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongoose\\lib\\connection.js:791:11)\n    at async connectDatabase (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/config/database.js:54:5)\n    at async startServer (file:///C:/Users/toxonicon/Desktop/Defect%20Traker/backend/src/server.js:82:5)","timestamp":"2025-10-01 13:57:21"}
{"level":"error","message":"MongoDB connection error: connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"service":"defect-tracker-backend","stack":"MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at Timeout._onTimeout (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\mongodb\\lib\\sdam\\topology.js:278:38)\n    at listOnTimeout (node:internal/timers:588:17)\n    at process.processTimers (node:internal/timers:523:7)","timestamp":"2025-10-01 13:57:21"}
{"level":"error","message":"❌ Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 09:12:31"}
{"level":"error","message":"Failed to start server: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 09:12:31"}
{"level":"error","message":"❌ Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 09:27:53"}
{"level":"error","message":"❌ Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 09:36:48"}
{"level":"error","message":"Failed to start server: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 09:36:48"}
{"level":"error","message":"❌ Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 09:43:58"}
{"level":"error","message":"Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 09:43:58"}
{"level":"error","message":"❌ Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 09:48:26"}
{"level":"error","message":"Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 09:48:26"}
{"level":"error","message":"❌ Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 10:05:50"}
{"level":"error","message":"Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 10:05:51"}
{"level":"error","message":"❌ Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 10:09:47"}
{"level":"error","message":"Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 10:09:47"}
{"level":"error","message":"❌ Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 10:11:39"}
{"level":"error","message":"Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 10:11:39"}
{"level":"error","message":"❌ Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 10:22:28"}
{"level":"error","message":"Failed to connect to PostgreSQL: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":120,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"service":"defect-tracker-backend","stack":"SequelizeConnectionError: ������������ \"postgres\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\toxonicon\\Desktop\\Defect Traker\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-10-08 10:22:28"}
